List<Map> explore_1 = [
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1881282,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]【全方位无死角的保姆式旅游攻略第1期】川西三日游",
    "subject": "全方位无死角的保姆式旅游攻略第1期：川西三日游  楼主一",
    "user_id": 192153,
    "last_reply_date": "1627489563000",
    "user_nick_name": "冯虚",
    "hits": 8294,
    "replies": 96,
    "top": 1,
    "status": 32,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=192153&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1866376,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]【西门吃饭哪家强】",
    "subject": "探店这活就不适合我，太累了，这还没放图呢    火锅去鼎",
    "user_id": 230784,
    "last_reply_date": "1622181485000",
    "user_nick_name": "成电已五年",
    "hits": 32123,
    "replies": 270,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230784&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1860488,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]成都本地人的美食收藏",
    "subject": "首先楼主介绍一下自己~从小学到研究生待在成都十几二十年了",
    "user_id": 227979,
    "last_reply_date": "1620202946000",
    "user_nick_name": "皮皮露",
    "hits": 22329,
    "replies": 367,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=227979&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1854615,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]干饭人的饮食记录--不定期更新（停止更新了~）",
    "subject": "作为一个干饭人，我想努力把学校和龙湖商圈的餐饮店铺都尝试",
    "user_id": 240427,
    "last_reply_date": "1618136447000",
    "user_nick_name": "苦瓜炒鸡蛋",
    "hits": 7922,
    "replies": 107,
    "top": 1,
    "status": 32,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=240427&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1853571,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]记录那些年我打卡过的店",
    "subject": "一直都对美食十分热爱，记录一下打卡过的店~  个人口味：",
    "user_id": 92561,
    "last_reply_date": "1617790289000",
    "user_nick_name": "不爱梨",
    "hits": 3272,
    "replies": 28,
    "top": 1,
    "status": 32800,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=92561&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1853241,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]吃喝玩乐推荐，大部分是市内。",
    "subject": "昨天有朋友问我成都吃喝玩乐有什么推荐，就简单整理了一下 ",
    "user_id": 232593,
    "last_reply_date": "1617701428000",
    "user_nick_name": "Fourseasons",
    "hits": 12960,
    "replies": 53,
    "top": 1,
    "status": 32768,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=232593&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1835892,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]稻城亚丁，一个去过就不想再去的地方",
    "subject": "下山不断听到人说，“再也不来了”。  不想再来主要是作为",
    "user_id": 142507,
    "last_reply_date": "1609935908000",
    "user_nick_name": "自燃物",
    "hits": 6926,
    "replies": 44,
    "top": 1,
    "status": 32,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=142507&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1821116,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]萌新美食推荐(长期贴—日更)",
    "subject": "这里是吃货的聚集地，  我是成电美食雷达一枚，  作为成",
    "user_id": 238474,
    "last_reply_date": "1602593148000",
    "user_nick_name": "Bianca",
    "hits": 9960,
    "replies": 190,
    "top": 1,
    "status": 256,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=238474&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1819443,
    "type_id": 1115,
    "sort_id": 0,
    "title": "[吃喝]清水河龙湖二期餐饮点评更新至2020年10月",
    "subject": "龙湖二期已经开放了，河畔现有奖征集各家店铺的餐饮点评，好",
    "user_id": 189776,
    "last_reply_date": "1601469086000",
    "user_nick_name": "472036783",
    "hits": 11986,
    "replies": 146,
    "top": 1,
    "status": 32,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=189776&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 889263,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]搭车川藏",
    "subject": "——没有什么比未知更有趣，没有什么比希望更美好  题记：",
    "user_id": 20298,
    "last_reply_date": "1307088479000",
    "user_nick_name": "bingo",
    "hits": 886,
    "replies": 33,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=20298&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 712614,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]我的墨脱初体验",
    "subject": "写了标题，觉得有点标题党的感觉，还是先说明一下，我没有到",
    "user_id": 20100,
    "last_reply_date": "1286868274000",
    "user_nick_name": "cerelean",
    "hits": 2922,
    "replies": 90,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=20100&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 91163,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]四川旅游详解（各旅游点简介+高清图片）",
    "subject": "四川旅游简介    四川位于中国西南腹地，面积48万平方",
    "user_id": 6093,
    "last_reply_date": "1215086854000",
    "user_nick_name": "wei_sy",
    "hits": 2452,
    "replies": 48,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=6093&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 87315,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]（原创）那些俺走过的地方，第1弹——四姑娘山",
    "subject": "废话在前  那台老电脑越来越不行了，于是开始转移数据，翻",
    "user_id": 10923,
    "last_reply_date": "1214825234000",
    "user_nick_name": "小淀粉",
    "hits": 1859,
    "replies": 63,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=10923&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 33662,
    "type_id": 1117,
    "sort_id": 0,
    "title": "[游戏]永远的回忆1永恒的经典-国产RPG历史回顾",
    "subject": "国产RPG历史回顾--转载加整理     先申明，此文无",
    "user_id": 9003,
    "last_reply_date": "1208856091000",
    "user_nick_name": "影之葉",
    "hits": 1645,
    "replies": 60,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=9003&size=middle",
    "special": 0
  }
];
List<Map> explore_2 = [
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 336183,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]有关电子设计和出国留学的问题大家可以来这里提问和讨论~",
    "subject": "刚刚交了毕业论文，我觉得吧，应该写点什么留在这里~   ",
    "user_id": 25955,
    "last_reply_date": "1244535027000",
    "user_nick_name": "mashed",
    "hits": 2902,
    "replies": 46,
    "top": 0,
    "status": 0,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=25955&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 610566,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]平静地离开成电",
    "subject": "不知道怎么分类，就发到这里吧！！！！    要走了，来到",
    "user_id": 2068,
    "last_reply_date": "1276322831000",
    "user_nick_name": "yeya2007",
    "hits": 932,
    "replies": 24,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=2068&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1576624,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]七年之痒-将别，our UESTC",
    "subject": "《七年》  及冠五载将别去，前路或许多磨砺。七年之痒出肺",
    "user_id": 67962,
    "last_reply_date": "1449147236000",
    "user_nick_name": "邓意峰",
    "hits": 1936,
    "replies": 67,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=67962&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1609934,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]上一次见你还是七年前",
    "subject": "上一场毕业，是在三年前，只是毫无毕业的感觉，心里想着还要",
    "user_id": 52871,
    "last_reply_date": "1465189371000",
    "user_nick_name": "lemanyuan",
    "hits": 3128,
    "replies": 75,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=52871&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1662547,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]过来人给师弟妹们谈谈湿胸对研究生生涯见解",
    "subject": "考研选导师：注重导师的人品而轻视导师的学术！一直以来的教",
    "user_id": 154840,
    "last_reply_date": "1494577429000",
    "user_nick_name": "www.5d**.cn",
    "hits": 2865,
    "replies": 47,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=154840&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1671110,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]要毕业了，总要发些感慨",
    "subject": "我坐在这里，这个寝室，我待了三年。而清水河则容纳了我八年",
    "user_id": 56295,
    "last_reply_date": "1498217033000",
    "user_nick_name": "lirobin",
    "hits": 1466,
    "replies": 40,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=56295&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1672413,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]毕业想为学校正正名",
    "subject": "马上要离开呆了7年的学校，心中颇有点感伤    这不是一",
    "user_id": 30508,
    "last_reply_date": "1498579977000",
    "user_nick_name": "idge2008",
    "hits": 3292,
    "replies": 62,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=30508&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1672860,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]离校感怀——最后浪一把，从此我点成泥点",
    "subject": "庚寅年甲申月，秋，吾自江州入蜀，志学，缘成电。逝者如斯，",
    "user_id": 149602,
    "last_reply_date": "1498721426000",
    "user_nick_name": "张桥",
    "hits": 1119,
    "replies": 29,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=149602&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1703053,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]毕设水完，不想再做项目的水硕",
    "subject": "七年光景，水河畔的次数屈指可数。想着快毕业了，给自己留点",
    "user_id": 132135,
    "last_reply_date": "1517145560000",
    "user_nick_name": "delphinexh",
    "hits": 2544,
    "replies": 52,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=132135&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1768678,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]成电再见",
    "subject": "12年9月，怀着忐忑和期待步入校园，第一次感受到了南门到",
    "user_id": 131310,
    "last_reply_date": "1561728401000",
    "user_nick_name": "飘渺的黑夜",
    "hits": 2217,
    "replies": 37,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=131310&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1863705,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]好想念清水河啊",
    "subject": "毕业快2年了，最近频频想起在学校的快乐时光，在清水河6年",
    "user_id": 152887,
    "last_reply_date": "1621306695000",
    "user_nick_name": "Tinyrat",
    "hits": 934,
    "replies": 12,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=152887&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1874549,
    "type_id": 633,
    "sort_id": 0,
    "title": "[七年寒窗]再见，成电。再见，青春。",
    "subject": "7年的成电生涯马上就快结束了 不知道为啥 今晚特别伤感 ",
    "user_id": 237544,
    "last_reply_date": "1651325942000",
    "user_nick_name": "admin",
    "hits": 5655,
    "replies": 59,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=237544&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 359613,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]喝下这杯酒",
    "subject": "是什么，让我胸中涌出千言万语却不知从何说起?  是什么，",
    "user_id": 11468,
    "last_reply_date": "1246121720000",
    "user_nick_name": "无心悟道",
    "hits": 787,
    "replies": 10,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=11468&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 364147,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]老学生写给小毕业生的话",
    "subject": "即将毕业的同学们：你们好。    &nbsp; ",
    "user_id": 13395,
    "last_reply_date": "1246412944000",
    "user_nick_name": "一滴清水",
    "hits": 2318,
    "replies": 43,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=13395&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 365365,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]再看一眼清水河吧 我走了",
    "subject": "明天下午就离开这个学校了，很多人，很多事，都无时无刻出现",
    "user_id": 20308,
    "last_reply_date": "1246470158000",
    "user_nick_name": "二十三划生",
    "hits": 1218,
    "replies": 29,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=20308&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 554121,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]什么是母校？就是那个你一天骂他八遍却不许别人骂的地方--献给毕业班的同学",
    "subject": "1.什么是母校？就是那个你一天骂他八遍却不许别人骂的地方",
    "user_id": 41400,
    "last_reply_date": "1270970140000",
    "user_nick_name": "saiyang",
    "hits": 901,
    "replies": 18,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=41400&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 570428,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]我要毕业了",
    "subject": "看到同级人的感言，按捺不住心中的感慨。  我要毕业了。 ",
    "user_id": 24171,
    "last_reply_date": "1272615549000",
    "user_nick_name": "水木曦",
    "hits": 548,
    "replies": 13,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=24171&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 622627,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]栀子花开",
    "subject": "三周前的某天下午，天空罕见的晴朗，万里无云，于是我心情大",
    "user_id": 47047,
    "last_reply_date": "1277042747000",
    "user_nick_name": "andnot",
    "hits": 368,
    "replies": 3,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=47047&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 639222,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]明天，轮到我离开了",
    "subject": "明天还是来了，没想到会这么快！成都，离开家第一个来过的地",
    "user_id": 16762,
    "last_reply_date": "1277992420000",
    "user_nick_name": "xiaoxin",
    "hits": 453,
    "replies": 15,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=16762&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 639302,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]哥要走了，也来说说",
    "subject": "明天就要走了，也来水水吧！！！    今天去图书馆看了最",
    "user_id": 12665,
    "last_reply_date": "1277994986000",
    "user_nick_name": "xiaonanhai",
    "hits": 717,
    "replies": 22,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=12665&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 639492,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]毕业了，希望未来一切安好",
    "subject": "[wmv=1]http://attach.stuhome",
    "user_id": 180,
    "last_reply_date": "1278002703000",
    "user_nick_name": "南の柯",
    "hits": 367,
    "replies": 3,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=180&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 666770,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]在成电的几点感慨",
    "subject": "早上看到一个帖子，然后随手写了几点，不全面，语言逻辑也可",
    "user_id": 57429,
    "last_reply_date": "1281322776000",
    "user_nick_name": "llw",
    "hits": 1680,
    "replies": 29,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=57429&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 646100,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]四年，我们宛若清水河中一片涟漪",
    "subject": "随着国防生调令的下达，班里最后留下的国防生筒子们也勇闯天",
    "user_id": 14057,
    "last_reply_date": "1278499926000",
    "user_nick_name": "海边",
    "hits": 653,
    "replies": 12,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=14057&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 911605,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]我的四年感言",
    "subject": "    一直想写写自己的经",
    "user_id": 23620,
    "last_reply_date": "1308934158000",
    "user_nick_name": "marco",
    "hits": 1065,
    "replies": 22,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=23620&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 916101,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]今天授位了，今天毕业了，UESTC，七年了",
    "subject": "今天授位了，今天毕业了，UESTC，七年了，明天领证，后",
    "user_id": 19995,
    "last_reply_date": "1309245434000",
    "user_nick_name": "sxiao",
    "hits": 2080,
    "replies": 23,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=19995&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 946754,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]夜回河畔",
    "subject": "&nbsp;&nbsp;&nbs",
    "user_id": 33032,
    "last_reply_date": "1314046715000",
    "user_nick_name": "xiongxin324",
    "hits": 402,
    "replies": 9,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=33032&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 956453,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]你必须非常努力，才能看起来毫不费力，人与人才差距就在点点滴滴",
    "subject": "有一个很浪漫的故事  有一群人，他们积极自律，每天按计划",
    "user_id": 64905,
    "last_reply_date": "1315118361000",
    "user_nick_name": "fly2010",
    "hits": 2505,
    "replies": 41,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=64905&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 995996,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]成电四年",
    "subject": "毕业到现在已经叁多月了，早就打算写点东西，为自己的大学画",
    "user_id": 6599,
    "last_reply_date": "1319369595000",
    "user_nick_name": "calledwd",
    "hits": 5688,
    "replies": 146,
    "top": 0,
    "status": 512,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=6599&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1132657,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]《最后》，献给即将滚蛋的自己",
    "subject": "《最后》，献给即将滚蛋的自己      想忘记，过去的冲",
    "user_id": 27861,
    "last_reply_date": "1337567771000",
    "user_nick_name": "iamchenlei",
    "hits": 522,
    "replies": 3,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=27861&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1296125,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]【转载】是起点也是终点，是开始也是结束；是欢聚也是离散，是出发也是归宿。",
    "subject": "月台  是起点也是终点，是开始也是结束；是欢聚也是离散，",
    "user_id": 60206,
    "last_reply_date": "1365751887000",
    "user_nick_name": "stupidfish",
    "hits": 361,
    "replies": 3,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=60206&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1435637,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]故事里的事",
    "subject": "从入学到仅剩一个多月毕业，第一次在河畔上撰文，空间里的日",
    "user_id": 102121,
    "last_reply_date": "1400352431000",
    "user_nick_name": "1509195657",
    "hits": 2368,
    "replies": 114,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=102121&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1436879,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]致我终将毕业的大学",
    "subject": "写论文写到吐。。。然后就想回顾下在神技大学的四年，致我终",
    "user_id": 98359,
    "last_reply_date": "1400682789000",
    "user_nick_name": "阿离",
    "hits": 3630,
    "replies": 216,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=98359&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1439806,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]你不敢想明天 ，我不敢说再见。",
    "subject": "刚来这里的那年，看大四学姐学长拖箱子离开学校，感觉离我们",
    "user_id": 121030,
    "last_reply_date": "1401436110000",
    "user_nick_name": "撒了个泼的",
    "hits": 1920,
    "replies": 97,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=121030&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1441250,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]学渣毕业流水账",
    "subject": "《老考生》最后附上一首自己大一时候录的歌《老考生》，跑调",
    "user_id": 92729,
    "last_reply_date": "1401814330000",
    "user_nick_name": "狂风游魂",
    "hits": 3441,
    "replies": 142,
    "top": 0,
    "status": 800,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=92729&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1445731,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]再见",
    "subject": "一首陪伴了四年的'暗里着迷’，一个大二分手后买的背包，一",
    "user_id": 154433,
    "last_reply_date": "1402910934000",
    "user_nick_name": "fantasy-lee",
    "hits": 324,
    "replies": 4,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=154433&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1451056,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]毕业感言这种东西我怎么可能会写",
    "subject": "但是啊,   九点多,    靠着黄色路灯一盏接一盏的3",
    "user_id": 98119,
    "last_reply_date": "1403875378000",
    "user_nick_name": "geek_beta",
    "hits": 353,
    "replies": 7,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=98119&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1451288,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]钻石Diamond丶毕业感言",
    "subject": "下雨,整个人都懒懒的,跟蒲巅峰的风,听二哥哥的歌,写毕业",
    "user_id": 130703,
    "last_reply_date": "1403935662000",
    "user_nick_name": "钻石Diamond丶",
    "hits": 2079,
    "replies": 244,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=130703&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1529253,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]吐槽一下我四年的大学生涯（流水账）",
    "subject": "今天看到很多同学发毕业集体照了，在公司上班的我只能暗自伤",
    "user_id": 134472,
    "last_reply_date": "1433767706000",
    "user_nick_name": "转身向左",
    "hits": 705,
    "replies": 33,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=134472&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1531979,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]请抓住我的手，回到四年前",
    "subject": "抓住我的手，回到四年前    文|           ",
    "user_id": 115739,
    "last_reply_date": "1434386949000",
    "user_nick_name": "江湖小虾米",
    "hits": 1708,
    "replies": 43,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=115739&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1639231,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]学就学好，找工作就找大公司，要谈就谈工资，别说前景",
    "subject": "第一次发帖，由于个人经历有限，认知有限，难免有些地方以偏",
    "user_id": 66915,
    "last_reply_date": "1480144504000",
    "user_nick_name": "笑月残尸",
    "hits": 4493,
    "replies": 70,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=66915&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1658826,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]高考之后的1500天",
    "subject": "高中热爱古典诗词，一口一个长风破浪会有时，直挂云帆济沧海",
    "user_id": 182192,
    "last_reply_date": "1492504988000",
    "user_nick_name": "扫地僧88",
    "hits": 1766,
    "replies": 78,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=182192&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1662980,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]毕业感想篇：庸俗的小刘（说说我的失败让你们开心开心）",
    "subject": "记得四年前曾说过学不成名誓不还的豪言壮语。当时很年轻，总",
    "user_id": 182192,
    "last_reply_date": "1494821175000",
    "user_nick_name": "扫地僧88",
    "hits": 3317,
    "replies": 91,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=182192&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1723593,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]青春万岁，永远不老———毕业晚会真的很好看啊",
    "subject": "毕业那年，因为提前到公司实习，错过了毕业晚会。一直是一个",
    "user_id": 102582,
    "last_reply_date": "1529852386000",
    "user_nick_name": "ssaa",
    "hits": 615,
    "replies": 13,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=102582&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1758302,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]一位不愿意透露姓名的大四老学姐路过",
    "subject": "还有两个多月就要毕业，大学究竟做了什么呢？没有科研，没有",
    "user_id": 224056,
    "last_reply_date": "1555595964000",
    "user_nick_name": "tangtangtangg",
    "hits": 4938,
    "replies": 155,
    "top": 0,
    "status": 40,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=224056&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1804876,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]大学回顾，部分悲惨的大学生涯。",
    "subject": "专门换了一个号来写一次回顾。原本早就想写的，但是最近天天",
    "user_id": 218181,
    "last_reply_date": "1592779994000",
    "user_nick_name": "假如测试的",
    "hits": 8047,
    "replies": 133,
    "top": 0,
    "status": 0,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=218181&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1811050,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]大学四年，平平无奇。",
    "subject": "今天20年八月十号，我已经毕业了。晚上坐在电脑前太无聊了",
    "user_id": 200298,
    "last_reply_date": "1597065070000",
    "user_nick_name": "824218055",
    "hits": 2330,
    "replies": 41,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=200298&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 237,
    "board_name": "毕业感言",
    "topic_id": 1872981,
    "type_id": 631,
    "sort_id": 0,
    "title": "[四年回顾]别了，成电",
    "subject": "说明:三月份应辅导员之邀写的一篇分享，下周就毕业了，希望",
    "user_id": 213035,
    "last_reply_date": "1624151826000",
    "user_nick_name": "渊澄",
    "hits": 2322,
    "replies": 11,
    "top": 0,
    "status": 32800,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=213035&size=middle",
    "special": 0
  }
];
List<Map> explore_3 = [
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1597505,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]2016年光电考上交通信819考研经历",
    "subject": "前言  这个帖子是流水账形式，记录我的考研过程。考研不易",
    "user_id": 146771,
    "last_reply_date": "1460215338000",
    "user_nick_name": "半月晨风",
    "hits": 723,
    "replies": 12,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=146771&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1597606,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]2016机电（本校本院）考研经验分享",
    "subject": "没想到居然还有人问我这种考研水笔经验...反正说都说了，",
    "user_id": 131536,
    "last_reply_date": "1460275410000",
    "user_nick_name": "callofdutyops",
    "hits": 487,
    "replies": 14,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=131536&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1602381,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]2016 zju 计算机考研经验分享",
    "subject": "先来打广告：出售考研书籍 http://bbs.uest",
    "user_id": 127570,
    "last_reply_date": "1462378907000",
    "user_nick_name": "zsrkmyn",
    "hits": 826,
    "replies": 7,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=127570&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1602628,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]不可预料———2016本校抗干扰考研经验贴",
    "subject": "不可预料    人呐就都不知道，自己不可以预料。    ",
    "user_id": 133306,
    "last_reply_date": "1462464480000",
    "user_nick_name": "格瓦拉",
    "hits": 1142,
    "replies": 14,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=133306&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1618887,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]考研经验分享",
    "subject": "最后作为一个历经两次考研的前辈只是想把自己的一些经验分享",
    "user_id": 195031,
    "last_reply_date": "1468557176000",
    "user_nick_name": "yanzi920324",
    "hits": 1066,
    "replies": 22,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=195031&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1656112,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]考研411经验分享",
    "subject": "随着2017考研的落幕，经过一年（其实没那么久）的学习，",
    "user_id": 201490,
    "last_reply_date": "1490946719000",
    "user_nick_name": "liuyuxiong123",
    "hits": 502,
    "replies": 14,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=201490&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1674454,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]我的保研历程",
    "subject": "保研过去已经接近两年了，期间一直想发个贴子骗骗水滴，无奈",
    "user_id": 125086,
    "last_reply_date": "1499585827000",
    "user_nick_name": "yeszoom59",
    "hits": 1574,
    "replies": 19,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=125086&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1733970,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]我的保研之路——中科院信工所",
    "subject": "先介绍一下背景：      年级：2015      学",
    "user_id": 200246,
    "last_reply_date": "1536762261000",
    "user_nick_name": "成电一隅",
    "hits": 7158,
    "replies": 118,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=200246&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1734389,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]保研分享---中科院计算所",
    "subject": "下面内容自身总结所得，有大量主观看法，不代表真实情况，不",
    "user_id": 207446,
    "last_reply_date": "1536979303000",
    "user_nick_name": "mate595",
    "hits": 844,
    "replies": 13,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=207446&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1830096,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]史上最全电子科技大学858信号与系统考研要了解的常识",
    "subject": "码字不易，感谢支持。  分享者专业课分数：140左右  ",
    "user_id": 204785,
    "last_reply_date": "1607359277000",
    "user_nick_name": "2015080105012",
    "hits": 8584,
    "replies": 18,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=204785&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1849524,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]2020年“工理经管”四大门类保研夏令营混申回忆录（清深...",
    "subject": "2020年的保研季处于新冠疫情席卷全球，国际形势充满动荡",
    "user_id": 214201,
    "last_reply_date": "1616471718000",
    "user_nick_name": "Jipeng416",
    "hits": 3202,
    "replies": 31,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=214201&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1850871,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]清华827考研分享（自动化电气人工智能）",
    "subject": "先上图自证清白：     前言18年的时候，我们学校有个",
    "user_id": 211591,
    "last_reply_date": "1616855597000",
    "user_nick_name": "南瓜不说话",
    "hits": 9992,
    "replies": 53,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=211591&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1855645,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]信通学院面试专业课资料分享【畔友投稿】",
    "subject": "友情提醒大家，不要将资料流传至校外其他同学，仅用于河畔内",
    "user_id": 189776,
    "last_reply_date": "1618474856000",
    "user_nick_name": "472036783",
    "hits": 12197,
    "replies": 58,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=189776&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1908992,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]电气电网专业保研考研选校经验分享（2）（完整版）",
    "subject": "上一期：  https://bbs.uestc.edu.",
    "user_id": 192153,
    "last_reply_date": "1638782074000",
    "user_nick_name": "冯虚",
    "hits": 900,
    "replies": 15,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=192153&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1916192,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]考研资料推荐",
    "subject": "虽然我一直觉得考研没必要太早开始，但为了给已经或者想开始",
    "user_id": 230162,
    "last_reply_date": "1641692319000",
    "user_nick_name": "1341272263",
    "hits": 3562,
    "replies": 52,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230162&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1920395,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]考研择校分析与推荐",
    "subject": "私以为，考研择校的重要性不比考研复习本身低，如果高考是“",
    "user_id": 230162,
    "last_reply_date": "1645498320000",
    "user_nick_name": "1341272263",
    "hits": 3451,
    "replies": 43,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230162&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1922668,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]浅谈清华电子系考研专业课命题趋势2010-2022",
    "subject": "在河畔留下这个帖子的目的是帮助有志于清华电子系的同学全面",
    "user_id": 207849,
    "last_reply_date": "1646792909000",
    "user_nick_name": "1415131913",
    "hits": 1697,
    "replies": 30,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=207849&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1925672,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]跨考上岸",
    "subject": "楼主中科大计算机电子信息拟录取，初试397，英一84，4",
    "user_id": 237990,
    "last_reply_date": "1648475750000",
    "user_nick_name": "aweiyyds",
    "hits": 4695,
    "replies": 48,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=237990&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1926106,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]也来分享一波考研外校经验",
    "subject": "从大二就开始水河畔啦，一直觉得河畔是一个很温暖的大家庭，",
    "user_id": 222119,
    "last_reply_date": "1648694875000",
    "user_nick_name": "焚岚小天天",
    "hits": 1046,
    "replies": 9,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=222119&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1927559,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]2022北大信工计算机应用技术经验分享",
    "subject": "大家好，我是泥点18级通信工程专业的老学长/小兄弟。今年",
    "user_id": 230162,
    "last_reply_date": "1649321346000",
    "user_nick_name": "1341272263",
    "hits": 4179,
    "replies": 52,
    "top": 1,
    "status": 32,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230162&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1927848,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]考研资料分享",
    "subject": "楼主是今年浙大录取了，今天晚上整理了一下自己的资料。在自",
    "user_id": 236891,
    "last_reply_date": "1649428082000",
    "user_nick_name": "清小水",
    "hits": 1566,
    "replies": 18,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=236891&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1929181,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]22信通考研经验分享",
    "subject": "楼主本科本校电子信息工程，初试394（76+72+120",
    "user_id": 251346,
    "last_reply_date": "1649989345000",
    "user_nick_name": "2018151202014",
    "hits": 1037,
    "replies": 16,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=251346&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 199,
    "board_name": "保研考研",
    "topic_id": 1932138,
    "type_id": 215,
    "sort_id": 0,
    "title": "[经验分享]南大电院专硕上岸攻略贴",
    "subject": "lz今年专业第一上岸南大电院，给想run外校的兄弟们指个",
    "user_id": 233271,
    "last_reply_date": "1651193520000",
    "user_nick_name": "一夜十三郎z",
    "hits": 681,
    "replies": 14,
    "top": 0,
    "status": 32,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=233271&size=middle",
    "special": 0
  }
];
List<Map> explore_4 = [
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 60209,
    "type_id": 393,
    "sort_id": 0,
    "title": "[倾诉]心动",
    "subject": "记得那个镜头：寒风凛冽的东京街头，昏暗的街角巷口，鞋底扣",
    "user_id": 939,
    "last_reply_date": "1212687229000",
    "user_nick_name": "情感大狗",
    "hits": 1928,
    "replies": 24,
    "top": 0,
    "status": 256,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=939&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1677323,
    "type_id": 393,
    "sort_id": 0,
    "title": "[倾诉]心动不是爱情，心静才是  8.24   1.92更",
    "subject": "【个人经历，只在河畔分享，谢绝任何形式的转载引用，谢谢】",
    "user_id": 186058,
    "last_reply_date": "1502076896000",
    "user_nick_name": "ur_smile",
    "hits": 3716,
    "replies": 58,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=186058&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1799779,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]我和我老公的八周年",
    "subject": "睡不着，就写写罗～其实应该是我和我老公恋爱的第八年～上周",
    "user_id": 114197,
    "last_reply_date": "1590689611000",
    "user_nick_name": "你好我们",
    "hits": 4305,
    "replies": 64,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=114197&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1820762,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]谢谢你，真的（写于认识十年时）",
    "subject": "十一长假后的第一个休息日，整理一篇文字，记录和一个异性朋",
    "user_id": 36512,
    "last_reply_date": "1602415766000",
    "user_nick_name": "thanks",
    "hits": 79169,
    "replies": 174,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=36512&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1822721,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]甜甜的爱情可算正式开始了",
    "subject": "这是上一集《甜甜的爱情终于轮到我了》  甜甜的爱情需要一",
    "user_id": 227995,
    "last_reply_date": "1603470339000",
    "user_nick_name": "bobdzy",
    "hits": 1969,
    "replies": 47,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=227995&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1829799,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]这周和小姐姐在一起了",
    "subject": "嘻嘻 两电一家亲，先开个帖子，等空了再来记录。  追逐心",
    "user_id": 181180,
    "last_reply_date": "1607229917000",
    "user_nick_name": "Rencontra",
    "hits": 5664,
    "replies": 65,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=181180&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1828875,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]【双H记】真·水河畔可以脱单",
    "subject": "首先感谢   发的帖子《有好的交友脱单渠道吗》传送门  ",
    "user_id": 239363,
    "last_reply_date": "1606721861000",
    "user_nick_name": "不插电的刺猬",
    "hits": 5269,
    "replies": 92,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=239363&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1829806,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]【周更帖.】第六弹～这次川师小学妹过来了泥电",
    "subject": "周五下午考完组合，啪得一下很快啊，我就去西门有轨电车站台",
    "user_id": 198833,
    "last_reply_date": "1607232280000",
    "user_nick_name": "第三次浪潮",
    "hits": 8370,
    "replies": 116,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=198833&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1830443,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]【双H记】吹响表白的冲锋号",
    "subject": "发过三篇之后还挺多畔友跟我说想继续看我写这个系列的哈哈哈",
    "user_id": 239363,
    "last_reply_date": "1607505237000",
    "user_nick_name": "不插电的刺猬",
    "hits": 4509,
    "replies": 91,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=239363&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1833776,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]这是一个很重要的标题！！！",
    "subject": "俺是楼主的妹子（还是很奇怪的开场白）    啊啊啊啊 今",
    "user_id": 199835,
    "last_reply_date": "1608982429000",
    "user_nick_name": "z828849eser",
    "hits": 2279,
    "replies": 38,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=199835&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1833806,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]【周更贴7】平安夜也是她的生日，终于补了表白仪式",
    "subject": "其实说来好奇怪，感觉我和小学妹真的像是万圣节第一天见面就",
    "user_id": 198833,
    "last_reply_date": "1608994646000",
    "user_nick_name": "第三次浪潮",
    "hits": 3833,
    "replies": 94,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=198833&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1836719,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]再来杀一次",
    "subject": "昨天到的广州，要在这边住半个月，就住了个酒店。今天老婆给",
    "user_id": 195744,
    "last_reply_date": "1610346531000",
    "user_nick_name": "滴，学生卡",
    "hits": 3970,
    "replies": 97,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=195744&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1836121,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]和npy缩在帽子里看雪，多美好啊",
    "subject": "可可爱爱，没有脑袋",
    "user_id": 227995,
    "last_reply_date": "1610031166000",
    "user_nick_name": "bobdzy",
    "hits": 1823,
    "replies": 32,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=227995&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1839500,
    "type_id": 395,
    "sort_id": 0,
    "title": "[表白]怎么会有我npy这么好的男孩纸",
    "subject": "今天是我们在一起的第99天，在这个特别的日子里，好想夸一",
    "user_id": 238662,
    "last_reply_date": "1611940028000",
    "user_nick_name": "月亮上的蓝耳兔",
    "hits": 6221,
    "replies": 80,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=238662&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 307,
    "board_name": "镜头下的成电",
    "topic_id": 1855698,
    "type_id": 0,
    "sort_id": 0,
    "title": "成电情侣写真｜我愿称其为成电最绝美的爱情",
    "subject": "“思念如马，自别离，未停蹄。”  这次是一对大学异地恋四",
    "user_id": 240017,
    "last_reply_date": "1618488191000",
    "user_nick_name": "啊啊啊邱湫_",
    "hits": 9291,
    "replies": 109,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=240017&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1855783,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]ℹ️🐧",
    "subject": "谢谢宝贝，我好幸福",
    "user_id": 237919,
    "last_reply_date": "1618512515000",
    "user_nick_name": "无情东北人",
    "hits": 1622,
    "replies": 31,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=237919&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1856022,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]河畔开始的爱情💑（一）",
    "subject": "只想记录下我们美好的爱情，也鼓励大家为爱勇敢一点。  我",
    "user_id": 245142,
    "last_reply_date": "1618586579000",
    "user_nick_name": "芋泥啵啵",
    "hits": 9692,
    "replies": 120,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=245142&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1877200,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]长跑7年结婚啦",
    "subject": "跟老公恋爱七年，其中异地六年，今年在恋爱纪念日结婚啦！ ",
    "user_id": 230013,
    "last_reply_date": "1625448803000",
    "user_nick_name": "范老莫",
    "hits": 7867,
    "replies": 156,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230013&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1912210,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]2000片，好看(｡･ω･｡)ﾉ♡",
    "subject": "虽然在这个拼图拼好之前我们就在一起了，但这件我觉得很有意",
    "user_id": 224473,
    "last_reply_date": "1640087131000",
    "user_nick_name": "pocsnliuzx",
    "hits": 7310,
    "replies": 69,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=224473&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 55,
    "board_name": "视觉艺术",
    "topic_id": 1913312,
    "type_id": 350,
    "sort_id": 0,
    "title": "[原创-人文]考场门口有人在等你啊",
    "subject": "感动常在",
    "user_id": 220229,
    "last_reply_date": "1640520250000",
    "user_nick_name": "paperman",
    "hits": 5850,
    "replies": 60,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=220229&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1922960,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]河畔上捡到的宝藏男孩",
    "subject": "明天乐乐姐要出去玩，今天很开心，给畔友分享一件喜事——我",
    "user_id": 253726,
    "last_reply_date": "1646917704000",
    "user_nick_name": "乐乐樂了姐",
    "hits": 15543,
    "replies": 162,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=253726&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1923457,
    "type_id": 0,
    "sort_id": 0,
    "title": "女朋友信到了",
    "subject": "不小的人了还是喜欢搞这些可可爱爱的东西🥰🥰🥰🥰🥰🥰  所",
    "user_id": 251345,
    "last_reply_date": "1647239746000",
    "user_nick_name": "江南ofo",
    "hits": 2321,
    "replies": 30,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=251345&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1926933,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]不想在朋友圈张扬，但我可以跟河畔的朋友一起体验恋爱的快乐",
    "subject": "自从她说要好好吃早饭，我天天七点多爬起来去食堂，然后赖床",
    "user_id": 248375,
    "last_reply_date": "1649129355000",
    "user_nick_name": "久闻其名",
    "hits": 6372,
    "replies": 57,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=248375&size=middle",
    "special": 0
  }
];
List<Map> explore_5 = [
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1783901,
    "type_id": 396,
    "sort_id": 0,
    "title": "[讨论]商业街药店的万艾可",
    "subject": "如题，学校的商业街药店门口为啥放着万艾可的打折标签，学生",
    "user_id": 205655,
    "last_reply_date": "1573948267000",
    "user_nick_name": "沉默的石头",
    "hits": 49585,
    "replies": 403,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=205655&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1794686,
    "type_id": 319,
    "sort_id": 0,
    "title": "[求助]这都阿姨了，怎么可能是小姐姐？难道我眼花了",
    "subject": "不像小姐姐啊，估计都有几个孩子了",
    "user_id": 214912,
    "last_reply_date": "1586255644000",
    "user_nick_name": "纯洁的小黑兔",
    "hits": 2799,
    "replies": 31,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=214912&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1796260,
    "type_id": 315,
    "sort_id": 0,
    "title": "[灌水]说一说成都的香艳套路",
    "subject": "看到一个339帖子有感，说一说成都的香艳套路。     ",
    "user_id": 219989,
    "last_reply_date": "1588149367000",
    "user_nick_name": "二狗哥",
    "hits": 4484,
    "replies": 97,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=219989&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1796504,
    "type_id": 319,
    "sort_id": 0,
    "title": "[求助]情趣内衣（睡衣）推荐",
    "subject": "河畔的大哥哥大姐姐们，有没有体验比较好的情趣内衣（睡衣）",
    "user_id": 229642,
    "last_reply_date": "1588428331000",
    "user_nick_name": "尼格",
    "hits": 4071,
    "replies": 82,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=229642&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1799114,
    "type_id": 320,
    "sort_id": 0,
    "title": "[原创]戴眼镜接吻是不是很不方便啊？",
    "subject": "一般先摘下眼睛？",
    "user_id": 206079,
    "last_reply_date": "1590372591000",
    "user_nick_name": "来河畔学♂习♂",
    "hits": 1777,
    "replies": 47,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206079&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1804289,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]推荐一个新发现的小雨衣牌子",
    "subject": "更新：64楼有看帖后的简单测评  ———————————",
    "user_id": 217425,
    "last_reply_date": "1592502210000",
    "user_nick_name": "heshijinghuang",
    "hits": 4436,
    "replies": 78,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=217425&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1826154,
    "type_id": 0,
    "sort_id": 0,
    "title": "联动无安全性行为，我来给大家推荐几款套套",
    "subject": "情侣之间一定要相互负责，别真的图一时爽快就搞不安全性行为",
    "user_id": 225722,
    "last_reply_date": "1651378302000",
    "user_nick_name": "admin",
    "hits": 3890,
    "replies": 54,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=225722&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1826963,
    "type_id": 393,
    "sort_id": 0,
    "title": "[倾诉]关于那个武大女博士第三弹",
    "subject": "之前为了让自己远离河畔，自己申请了禁言。但是最近两天又有",
    "user_id": 142732,
    "last_reply_date": "1605618861000",
    "user_nick_name": "猩红的魂球",
    "hits": 7659,
    "replies": 57,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=142732&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1828186,
    "type_id": 0,
    "sort_id": 0,
    "title": "佐田在Library发生肾么事了",
    "subject": "昨天我在图书馆正襟危坐的看书，突然来了两个人坐在我前面，",
    "user_id": 217314,
    "last_reply_date": "1606306820000",
    "user_nick_name": "Mr.T",
    "hits": 1705,
    "replies": 29,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=217314&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1832188,
    "type_id": 0,
    "sort_id": 0,
    "title": "闲逛的偶然发现",
    "subject": "早早来到教室，还没到上课的时间  所以从品学楼走出来，看",
    "user_id": 235001,
    "last_reply_date": "1608270788000",
    "user_nick_name": "lawbs",
    "hits": 1911,
    "replies": 34,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=235001&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1836270,
    "type_id": 315,
    "sort_id": 0,
    "title": "[灌水]基于芒果酒店的讨论",
    "subject": "对于南门的芒果酒店，想必大家都不陌生.大家怎么客观的评价",
    "user_id": 236164,
    "last_reply_date": "1610097104000",
    "user_nick_name": "damn_",
    "hits": 2961,
    "replies": 40,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=236164&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1839251,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]妹子这是啥意思",
    "subject": "比我小五岁的妹妹给我推荐国产区资源",
    "user_id": 217526,
    "last_reply_date": "1611773226000",
    "user_nick_name": "tomoya",
    "hits": 6980,
    "replies": 60,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=217526&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1849380,
    "type_id": 315,
    "sort_id": 0,
    "title": "[灌水]高德地图附近搜大学",
    "subject": "电子科技大学工训大楼  这配图就离谱",
    "user_id": 240171,
    "last_reply_date": "1616420872000",
    "user_nick_name": "彩彻区明",
    "hits": 2160,
    "replies": 29,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=240171&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1850739,
    "type_id": 391,
    "sort_id": 0,
    "title": "[转帖]孔乙己嫖娼记",
    "subject": "上海的会所的格局，是和别处不同的：都是当街一个曲尺形的大",
    "user_id": 205496,
    "last_reply_date": "1616821145000",
    "user_nick_name": "少年闰土",
    "hits": 1752,
    "replies": 10,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=205496&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 370,
    "board_name": "吃喝玩乐",
    "topic_id": 1853204,
    "type_id": 1116,
    "sort_id": 0,
    "title": "[旅游]聊一聊我去过的酒店，欢迎同好进来交流",
    "subject": "首先，出于安全和卫生角度的考虑，我只选择连锁品牌旗下的酒",
    "user_id": 243425,
    "last_reply_date": "1617694750000",
    "user_nick_name": "铜锣烧加钱哥",
    "hits": 10662,
    "replies": 101,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=243425&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 61,
    "board_name": "二手专区",
    "topic_id": 1873429,
    "type_id": 286,
    "sort_id": 0,
    "title": "[清水河-书籍资料]毕业出书、笔、杭闪X炮姐联名衣服 （和几个套套）",
    "subject": "有意加Q:825476811  毕业出书，5-10元杭闪",
    "user_id": 215733,
    "last_reply_date": "1624254172000",
    "user_nick_name": "caijiajie",
    "hits": 2231,
    "replies": 12,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=215733&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 61,
    "board_name": "二手专区",
    "topic_id": 1879473,
    "type_id": 291,
    "sort_id": 0,
    "title": "[清水河-生活用品]免费送👮‍♀️",
    "subject": "前几天搬寝室偶然发现3年前买了个这个预防万一，结果没用上",
    "user_id": 222633,
    "last_reply_date": "1626618957000",
    "user_nick_name": "PLLL",
    "hits": 10935,
    "replies": 36,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=222633&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 45,
    "board_name": "情感专区",
    "topic_id": 1880974,
    "type_id": 392,
    "sort_id": 0,
    "title": "[原创]发生关系前，拜托先了解相关知识",
    "subject": "刚刚看了一个关于体外射精会不会怀孕的帖子，也不管楼主是男",
    "user_id": 218896,
    "last_reply_date": "1627356288000",
    "user_nick_name": "一只云朵",
    "hits": 11753,
    "replies": 93,
    "top": 0,
    "status": 33024,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=218896&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1885240,
    "type_id": 0,
    "sort_id": 0,
    "title": "有没有好用的女用小玩具",
    "subject": "有的话可以给个链接么",
    "user_id": 210519,
    "last_reply_date": "1629369715000",
    "user_nick_name": "318360641",
    "hits": 5096,
    "replies": 33,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=210519&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 309,
    "board_name": "成电锐评",
    "topic_id": 1894827,
    "type_id": 69,
    "sort_id": 0,
    "title": "[社会新闻]北邮卷后，养一池子鲨鱼！你电男生要小心了",
    "subject": "刚刚在朋友那里看到一帖子，卷后为了成绩睡学霸。太狠了  ",
    "user_id": 219809,
    "last_reply_date": "1632814444000",
    "user_nick_name": "MrHunt",
    "hits": 15543,
    "replies": 120,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=219809&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 236,
    "board_name": "校园热点",
    "topic_id": 1898694,
    "type_id": 0,
    "sort_id": 0,
    "title": "一则友情提醒",
    "subject": "已入深秋，天气转凉，这里要请各位畔友节制一下，爱惜身体 ",
    "user_id": 250495,
    "last_reply_date": "1634635940000",
    "user_nick_name": "河畔党组成员",
    "hits": 3597,
    "replies": 21,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=250495&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1915158,
    "type_id": 319,
    "sort_id": 0,
    "title": "[求助]避孕相关",
    "subject": "大家都知道，那啥的时候带好套套就可以了，但是楼主最近发现",
    "user_id": 253507,
    "last_reply_date": "1641286859000",
    "user_nick_name": "yingyingb",
    "hits": 6478,
    "replies": 67,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=253507&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1923626,
    "type_id": 0,
    "sort_id": 0,
    "title": "真的不如涛涛",
    "subject": "最近的🍉此起彼伏啊，哈哈哈哈哈哈哈",
    "user_id": 235160,
    "last_reply_date": "1647324818000",
    "user_nick_name": "烟雨楼雾",
    "hits": 3617,
    "replies": 28,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=235160&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1927013,
    "type_id": 315,
    "sort_id": 0,
    "title": "[灌水]买车记",
    "subject": "最近忙来偷闲，看着大家伙都开起了车，搞得自己心里也痒痒，",
    "user_id": 234931,
    "last_reply_date": "1651377944000",
    "user_nick_name": "admin",
    "hits": 2838,
    "replies": 43,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=234931&size=middle",
    "special": 0
  }
];
List<Map> explore_6 = [
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 675490,
    "type_id": 237,
    "sort_id": 0,
    "title": "[企业八卦]企业黑名单【更新至2017年】禁止mark",
    "subject": "近日看到  发帖建议建立一个论坛的企业黑名单，看到很多童",
    "user_id": 29916,
    "last_reply_date": "1282797301000",
    "user_nick_name": "mousexia",
    "hits": 153767,
    "replies": 231,
    "top": 1,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=29916&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 70,
    "board_name": "程序员之家",
    "topic_id": 1493781,
    "type_id": 127,
    "sort_id": 0,
    "title": "[Java]【转自北邮人论坛】Java学习路线图",
    "subject": "1. 熟悉一种文本编辑器，比如Vim, Emacs, N",
    "user_id": 101245,
    "last_reply_date": "1421390404000",
    "user_nick_name": "漂泊的胡萝卜",
    "hits": 6508,
    "replies": 36,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=101245&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1676789,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]写给和我一样很水很水的同学",
    "subject": "1.坚定信念，一定会找到工作。但也不要太放松觉得找不到也",
    "user_id": 89735,
    "last_reply_date": "1501556252000",
    "user_nick_name": "夕阳那边",
    "hits": 4238,
    "replies": 45,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=89735&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1740769,
    "type_id": 1296,
    "sort_id": 0,
    "title": "[互联网/软件类]真正的没写过代码的人找软开的辛酸泪",
    "subject": "从2018年5月25日开始收到vivo的提前批通知开始，",
    "user_id": 206480,
    "last_reply_date": "1541233928000",
    "user_nick_name": "nifuqin",
    "hits": 4771,
    "replies": 69,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206480&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1776670,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]互联网30岁以上的校友们现在怎样了？",
    "subject": "能说说自己最近的状态吗？感谢啊",
    "user_id": 183785,
    "last_reply_date": "1567998329000",
    "user_nick_name": "bannerblade",
    "hits": 4323,
    "replies": 44,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=183785&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1779333,
    "type_id": 1296,
    "sort_id": 0,
    "title": "[互联网/软件类]野生程序员求职心路",
    "subject": "先说一下自己的情况，非科班硕士，研究生才接触编程，导师没",
    "user_id": 205302,
    "last_reply_date": "1569746515000",
    "user_nick_name": "八点半出发",
    "hits": 3410,
    "replies": 43,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=205302&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 70,
    "board_name": "程序员之家",
    "topic_id": 1791689,
    "type_id": 127,
    "sort_id": 0,
    "title": "[Java]小小白转JAVA",
    "subject": "难度如何？有推荐的书吗？",
    "user_id": 228030,
    "last_reply_date": "1583109291000",
    "user_nick_name": "ye111",
    "hits": 2654,
    "replies": 37,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=228030&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1792247,
    "type_id": 1296,
    "sort_id": 0,
    "title": "[互联网/软件类]阿里求职经验分享",
    "subject": "1.个人情况      2015年成电计算机学院应用技术",
    "user_id": 129990,
    "last_reply_date": "1583643251000",
    "user_nick_name": "2010zjyy",
    "hits": 869,
    "replies": 9,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=129990&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1792930,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]写给想进互联网大厂当程序员的学习学妹的一些建议",
    "subject": "前言：       楼主不是计算机学院的，实验室也不是专",
    "user_id": 206934,
    "last_reply_date": "1584333986000",
    "user_nick_name": "幽它一默1",
    "hits": 3455,
    "replies": 56,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206934&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1793001,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]【职场这些年踩过的坑】关于向上管理的重要性！！",
    "subject": "之前，由于工作变动，感慨很多，发了个帖子，很多学弟学妹咨",
    "user_id": 93445,
    "last_reply_date": "1584404754000",
    "user_nick_name": "panpan",
    "hits": 3786,
    "replies": 46,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=93445&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1797333,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]关于任正非说华为996，校友说几句",
    "subject": "回馈校友，希望仅限于内网讨论，由于同事很多也上河畔，就不",
    "user_id": 127624,
    "last_reply_date": "1651378700000",
    "user_nick_name": "admin",
    "hits": 10632,
    "replies": 168,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=127624&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 61,
    "board_name": "二手专区",
    "topic_id": 1801970,
    "type_id": 286,
    "sort_id": 0,
    "title": "[清水河-书籍资料]Java后端书籍 甩卖 附有 良心学习指导",
    "subject": "楼主是搞Java后端的，去年秋招签了杭州某大厂的java",
    "user_id": 206934,
    "last_reply_date": "1591637010000",
    "user_nick_name": "幽它一默1",
    "hits": 491,
    "replies": 9,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206934&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1810578,
    "type_id": 237,
    "sort_id": 0,
    "title": "[企业八卦]又到了一年一度的招聘季度了，大家可以尝试着投中学。",
    "subject": "不一定总是盯着互联网啊，体制内除了公务员还有很多好的选择",
    "user_id": 197071,
    "last_reply_date": "1596703348000",
    "user_nick_name": "carryman",
    "hits": 2357,
    "replies": 46,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=197071&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1812488,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]传统算法面经（推荐方向）+入职一个半月的心得体会",
    "subject": "找工作期间，在河畔受到各种大佬的帮助，现在写一些渣渣经验",
    "user_id": 222585,
    "last_reply_date": "1598063698000",
    "user_nick_name": "Echoes",
    "hits": 2952,
    "replies": 62,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=222585&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1812762,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]关于秋招之前的准备（非互联网）",
    "subject": "想把自己之前招聘遇到的问题分享下。如果不是一股脑的死磕互",
    "user_id": 197071,
    "last_reply_date": "1598261037000",
    "user_nick_name": "carryman",
    "hits": 1057,
    "replies": 21,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=197071&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1813525,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]说一说毕业一年踩的坑",
    "subject": "1.公积金问题。签三方之前要问清楚公积金基数，比如我上家",
    "user_id": 200385,
    "last_reply_date": "1598753558000",
    "user_nick_name": "数理方程",
    "hits": 5272,
    "replies": 57,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=200385&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1814938,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]20届非科班、材料器件、java菜鸡的普通硕士の求职心得",
    "subject": "又到一年一度的秋招了，大家也都在找工作了。作为一个20届",
    "user_id": 211223,
    "last_reply_date": "1599455105000",
    "user_nick_name": "uestc-masterV",
    "hits": 11675,
    "replies": 157,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=211223&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1815815,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]这几天内推了几个同学，说说有关简历的事",
    "subject": "这几天内推了好多同学，看着他们的简历，不自觉就想起去年这",
    "user_id": 135558,
    "last_reply_date": "1599749051000",
    "user_nick_name": "sjr1303",
    "hits": 1295,
    "replies": 10,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=135558&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 263,
    "board_name": "职场交流",
    "topic_id": 1816438,
    "type_id": 732,
    "sort_id": 0,
    "title": "[交流讨论]最真实的2021届找工作经历(干货)",
    "subject": "最真实的2021届找工作经历(干货)    写在前面： ",
    "user_id": 207008,
    "last_reply_date": "1600159331000",
    "user_nick_name": "扬帆起航",
    "hits": 1764,
    "replies": 33,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=207008&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1817540,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]谈谈自己找工作遇到的坑",
    "subject": "0、远离制造业，远离制造业，远离制造业！特别是机械制造相",
    "user_id": 206338,
    "last_reply_date": "1600575373000",
    "user_nick_name": "此号已注销",
    "hits": 3523,
    "replies": 50,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206338&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1817733,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]秋招末期如何找offer，三方、意向书、offer比较看这里",
    "subject": "现在已经是九月中下旬了，以往招聘的黄金时间就是9月10月",
    "user_id": 206050,
    "last_reply_date": "1600668122000",
    "user_nick_name": "yicheng",
    "hits": 2016,
    "replies": 36,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206050&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1818305,
    "type_id": 1296,
    "sort_id": 0,
    "title": "[互联网/软件类]Android学习历程秋招总结",
    "subject": "真正常硕的秋招总结，自己的基础并不是很好，今年能上岸其实",
    "user_id": 230570,
    "last_reply_date": "1600919840000",
    "user_nick_name": "一个普通的ID",
    "hits": 903,
    "replies": 21,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=230570&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 430,
    "board_name": "公考选调",
    "topic_id": 1820453,
    "type_id": 1348,
    "sort_id": 0,
    "title": "[备考经验分享]国家部委公务员考试国考上岸备考经验总结",
    "subject": "鉴于有同学询问备考经验和我个人的一些基本信息，所以我把相",
    "user_id": 101821,
    "last_reply_date": "1602254911000",
    "user_nick_name": "月却心",
    "hits": 7671,
    "replies": 125,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=101821&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1820620,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]【北漂2年】20届小学姐的互联网行业职场感悟",
    "subject": "（发帖子可太难了，可能是1年多没发帖子的惩罚？折腾了我2",
    "user_id": 206177,
    "last_reply_date": "1602342350000",
    "user_nick_name": "莫牙牙",
    "hits": 4942,
    "replies": 113,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=206177&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 430,
    "board_name": "公考选调",
    "topic_id": 1825320,
    "type_id": 1348,
    "sort_id": 0,
    "title": "[备考经验分享]给所有参加选调生考试的选手的一封建议书",
    "subject": "随着疫情，毕业人数等原因，现在找工作的难度越来越大，机会",
    "user_id": 205624,
    "last_reply_date": "1604740450000",
    "user_nick_name": "JChen",
    "hits": 6256,
    "replies": 63,
    "top": 0,
    "status": 33056,
    "essence": 0,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=205624&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1831595,
    "type_id": 1296,
    "sort_id": 0,
    "title": "[互联网/软件类]Java后端程序媛小白の秋招备考小攻略",
    "subject": "2020年转瞬即逝，距离自己三方寄出已经快两个月了，秋招",
    "user_id": 226269,
    "last_reply_date": "1608011014000",
    "user_nick_name": "BlingblingDu",
    "hits": 11266,
    "replies": 108,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=226269&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1834970,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]告别勤勉而坚定的2020，来跟师弟师妹唠叨几句",
    "subject": "2020年，我给自己的人生做了一些决定，在河畔分享了一些",
    "user_id": 93445,
    "last_reply_date": "1609477485000",
    "user_nick_name": "panpan",
    "hits": 2878,
    "replies": 17,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=93445&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1837228,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]闲来无事 聊聊我眼中的金融行业",
    "subject": "毕业几年回头看，对于自己当初误打误撞进入金融行业还是深感",
    "user_id": 146301,
    "last_reply_date": "1610587347000",
    "user_nick_name": "c5395348",
    "hits": 3768,
    "replies": 66,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=146301&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 25,
    "board_name": "水手之家",
    "topic_id": 1837400,
    "type_id": 315,
    "sort_id": 0,
    "title": "[灌水]关于研究所劝退的一些碎碎念感想",
    "subject": "想到哪儿写到哪儿，反正最近很忙，忙里偷闲的冒个泡  --",
    "user_id": 197071,
    "last_reply_date": "1610682263000",
    "user_nick_name": "carryman",
    "hits": 2501,
    "replies": 44,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=197071&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 214,
    "board_name": "招聘信息发布栏",
    "topic_id": 1838689,
    "type_id": 904,
    "sort_id": 0,
    "title": "[社招（社会招聘）]成都国企内推研发和综合岗位",
    "subject": "首先，我没有招聘权限，企业我也不能代表。所以在这里就不说",
    "user_id": 210613,
    "last_reply_date": "1611371644000",
    "user_nick_name": "201722240123",
    "hits": 1329,
    "replies": 8,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=210613&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1849624,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]跳槽季倒在字节门口，眼光放长远一点",
    "subject": "16届本科，工作也快满5年了。由于各种原因，兜兜转转，先",
    "user_id": 184574,
    "last_reply_date": "1616497345000",
    "user_nick_name": "Proudmoore",
    "hits": 20476,
    "replies": 173,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=184574&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1854388,
    "type_id": 235,
    "sort_id": 0,
    "title": "[求助讨论]分享一篇互联网秋招指南",
    "subject": "原文连接：     看到一篇比较详细全面的经验贴，分享给",
    "user_id": 225629,
    "last_reply_date": "1618046871000",
    "user_nick_name": "程灵胡",
    "hits": 7151,
    "replies": 72,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=225629&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1856861,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]国企经验分享",
    "subject": "LZ介绍一下个人情况，首先楼主并不是什么技术大牛，没有什",
    "user_id": 225722,
    "last_reply_date": "1618912243000",
    "user_nick_name": "C++primer",
    "hits": 25045,
    "replies": 173,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=225722&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1865351,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]【面经】Java找暑期实习总结",
    "subject": "写在前面的一些话：  墙裂建议想要去互联网做后端的同学直",
    "user_id": 213137,
    "last_reply_date": "1621858292000",
    "user_nick_name": "Morty_",
    "hits": 6712,
    "replies": 73,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=213137&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1874651,
    "type_id": 235,
    "sort_id": 0,
    "title": "[求助讨论]现在还是条条大路通java吗",
    "subject": "目前准研一，材料方向，问了问师兄就业情况，说是之前的师兄",
    "user_id": 212645,
    "last_reply_date": "1624507812000",
    "user_nick_name": "GFT",
    "hits": 7321,
    "replies": 45,
    "top": 0,
    "status": 256,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=212645&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1883196,
    "type_id": 1302,
    "sort_id": 0,
    "title": "[其他]国企类求职-小小的经验分享（央企篇）",
    "subject": "更新~~  小伙伴们，这个群早就人满了，我扩容之后很快又",
    "user_id": 223011,
    "last_reply_date": "1628428205000",
    "user_nick_name": "风稻妞",
    "hits": 11459,
    "replies": 111,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=223011&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1883610,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]国开补充信息&备考",
    "subject": "一，上一个帖子贴了国开的情况，针对大家感兴趣的补充一下：",
    "user_id": 216784,
    "last_reply_date": "1628605189000",
    "user_nick_name": "tyhxixi",
    "hits": 4748,
    "replies": 51,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=216784&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 430,
    "board_name": "公考选调",
    "topic_id": 1883949,
    "type_id": 1347,
    "sort_id": 0,
    "title": "[职场交流&职业选择]部委机关工作体验（仅供参考）",
    "subject": "【仅供内部学习交流使用，不用于其他任何目的，请勿转载，谢",
    "user_id": 101821,
    "last_reply_date": "1628769571000",
    "user_nick_name": "月却心",
    "hits": 10210,
    "replies": 233,
    "top": 1,
    "status": 288,
    "essence": 1,
    "hot": 1,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=101821&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1883981,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]秋招启示",
    "subject": "兄弟们，最近拿了一些厂的意向书，发觉这些厂并不是那么难进",
    "user_id": 229235,
    "last_reply_date": "1628779811000",
    "user_nick_name": "逍遥xjq",
    "hits": 2049,
    "replies": 25,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=229235&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1889446,
    "type_id": 235,
    "sort_id": 0,
    "title": "[求助讨论]迷茫求助，根据今年秋招情况，应该学C++还是JAVA呀？",
    "subject": "我开学研二，本硕都是成电的，计算机基础仅停留于本科的课。",
    "user_id": 223340,
    "last_reply_date": "1630922953000",
    "user_nick_name": "妙街十三少",
    "hits": 5482,
    "replies": 64,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=223340&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1892752,
    "type_id": 238,
    "sort_id": 0,
    "title": "[职业生涯分享]IC 求职经验贴",
    "subject": "水硕，真水硕，IC验证岗位  已有offer：中兴（16",
    "user_id": 227634,
    "last_reply_date": "1632040086000",
    "user_nick_name": "你好未来",
    "hits": 10836,
    "replies": 115,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=227634&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 395,
    "board_name": "藏经阁",
    "topic_id": 1893983,
    "type_id": 1303,
    "sort_id": 0,
    "title": "[硬件类]老学姐2021年数字IC秋招复盘",
    "subject": "本着学习交流的态度，写了下面的内容：  1、 秋招变春招",
    "user_id": 225916,
    "last_reply_date": "1632495453000",
    "user_nick_name": "红苹果jhwill",
    "hits": 6588,
    "replies": 35,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=225916&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1897142,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]超实用数字IC学习资源，来了~~~",
    "subject": "IC老学姐又来咯，今天为大家带来数字IC学习过程中必备资",
    "user_id": 225916,
    "last_reply_date": "1633954505000",
    "user_nick_name": "红苹果jhwill",
    "hits": 3923,
    "replies": 28,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=225916&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1899364,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]自学IC，我拿了20个offer和至少五家公司的40W+",
    "subject": "今年秋招即将拉下帷幕，也看到很多人在河畔上求助offer",
    "user_id": 228712,
    "last_reply_date": "1634904982000",
    "user_nick_name": "酒酒呀",
    "hits": 8559,
    "replies": 60,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=228712&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1900192,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]数字IC设计成长经验干活分享",
    "subject": "大家好，LZ我又来了，抱歉哈因为LZ秋招期间还要忙教研室",
    "user_id": 234465,
    "last_reply_date": "1635318155000",
    "user_nick_name": "201921021121",
    "hits": 6745,
    "replies": 68,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=234465&size=middle",
    "special": 0
  },
  {
    "pic_path": "",
    "board_id": 174,
    "board_name": "就业创业",
    "topic_id": 1900386,
    "type_id": 1170,
    "sort_id": 0,
    "title": "[求职心路]22届成电蓝剑水硕FPGA/数字IC/通信求职经历",
    "subject": "做FPGA无线通信的，投了FPGA、数字IC设计、通信算",
    "user_id": 238527,
    "last_reply_date": "1635408854000",
    "user_nick_name": "FPGA_Explorer",
    "hits": 5967,
    "replies": 60,
    "top": 0,
    "status": 288,
    "essence": 0,
    "hot": 0,
    "userAvatar":
        "https://bbs.uestc.edu.cn/uc_server/avatar.php?uid=238527&size=middle",
    "special": 0
  }
];

List<List<Map>> explore_data = [
  explore_1,
  explore_2,
  explore_3,
  explore_4,
  explore_5,
  explore_6,
];
